### PR TITLE
Upgrade kepler to alpha 3.0.0

### PR DESCRIPTION
**Pull request by justin-kleid**
Note: Had to downgrade react back to ver 16 to keep consistency with kepler. Also, added resolutions to keep deck.gl from being >= 8.9. Not sure if there is a better way of going about this / enforcing versions.

Version 8.9 causes the require() with ES modules error. See:
https://deck.gl/docs/upgrade-guide

I believe kepler also sets the resolution. e.g. in the demo app:
https://github.com/keplergl/kepler.gl/blob/master/examples/demo-app/package.json

### CODE REVIEW

**Comment by justin-kleid** [comment]
For a potential fix without enforcing specific deckgl versions:
https://deck.gl/docs/get-started/using-with-react#using-deckgl-with-ssr

**Comment by lixun910** [comment]
I am working on a solution to use yarn's workspaces to create a monorepo so that we can use kepler.gl as a submodule, in case we can change the source code of kepler.gl

**Comment by lixun910** [comment]
I made a lot of changes to create a monorepo. Let's go through this tomorrow to make sure it also runs fine on your side @justin-kleid

**Comment by lixun910** [comment]
@justin-kleid Let's pause working on this PR. You can focus on tweaking the UI for your presentation.

**Pull request merged**
